steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGISTRY/$_SERVICE:$_TAG'
      - '-t'
      - '$_REGISTRY/$_SERVICE:latest'
      - '-f'
      - '$_DOCKERFILE'
      - '.'
images:
  - '$_REGISTRY/$_SERVICE:$_TAG'
  - '$_REGISTRY/$_SERVICE:latest'
timeout: 900s
