// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/git.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryRequest) Reset() {
	*x = CreateRepositoryRequest{}
	mi := &file_proto_git_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryRequest) ProtoMessage() {}

func (x *CreateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*CreateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRepositoryRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateRepositoryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type CreateRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepositoryResponse) Reset() {
	*x = CreateRepositoryResponse{}
	mi := &file_proto_git_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepositoryResponse) ProtoMessage() {}

func (x *CreateRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepositoryResponse.ProtoReflect.Descriptor instead.
func (*CreateRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRepositoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRepositoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryRequest) Reset() {
	*x = DeleteRepositoryRequest{}
	mi := &file_proto_git_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryRequest) ProtoMessage() {}

func (x *DeleteRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRepositoryRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DeleteRepositoryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type DeleteRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRepositoryResponse) Reset() {
	*x = DeleteRepositoryResponse{}
	mi := &file_proto_git_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepositoryResponse) ProtoMessage() {}

func (x *DeleteRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepositoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRepositoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_proto_git_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{4}
}

func (x *ListBranchesRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ListBranchesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type BranchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CommitSha     string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchInfo) Reset() {
	*x = BranchInfo{}
	mi := &file_proto_git_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchInfo) ProtoMessage() {}

func (x *BranchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchInfo.ProtoReflect.Descriptor instead.
func (*BranchInfo) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{5}
}

func (x *BranchInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BranchInfo) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *BranchInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *BranchInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*BranchInfo          `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_proto_git_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{6}
}

func (x *ListBranchesResponse) GetBranches() []*BranchInfo {
	if x != nil {
		return x.Branches
	}
	return nil
}

type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FromRef       string                 `protobuf:"bytes,4,opt,name=from_ref,json=fromRef,proto3" json:"from_ref,omitempty"` // SHA or branch name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_proto_git_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBranchRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateBranchRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetFromRef() string {
	if x != nil {
		return x.FromRef
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CommitSha     string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_proto_git_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBranchResponse) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

type DeleteBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchRequest) Reset() {
	*x = DeleteBranchRequest{}
	mi := &file_proto_git_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchRequest) ProtoMessage() {}

func (x *DeleteBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBranchRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DeleteBranchRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeleteBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchResponse) Reset() {
	*x = DeleteBranchResponse{}
	mi := &file_proto_git_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchResponse) ProtoMessage() {}

func (x *DeleteBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchResponse.ProtoReflect.Descriptor instead.
func (*DeleteBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBranchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsRequest) Reset() {
	*x = ListCommitsRequest{}
	mi := &file_proto_git_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsRequest) ProtoMessage() {}

func (x *ListCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommitsRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ListCommitsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListCommitsRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ListCommitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommitsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail   string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	CommittedAt   string                 `protobuf:"bytes,5,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	FilesChanged  int32                  `protobuf:"varint,6,opt,name=files_changed,json=filesChanged,proto3" json:"files_changed,omitempty"`
	Additions     int32                  `protobuf:"varint,7,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int32                  `protobuf:"varint,8,opt,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInfo) Reset() {
	*x = CommitInfo{}
	mi := &file_proto_git_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfo) ProtoMessage() {}

func (x *CommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfo.ProtoReflect.Descriptor instead.
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{12}
}

func (x *CommitInfo) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *CommitInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CommitInfo) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *CommitInfo) GetCommittedAt() string {
	if x != nil {
		return x.CommittedAt
	}
	return ""
}

func (x *CommitInfo) GetFilesChanged() int32 {
	if x != nil {
		return x.FilesChanged
	}
	return 0
}

func (x *CommitInfo) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *CommitInfo) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

type ListCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitInfo          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsResponse) Reset() {
	*x = ListCommitsResponse{}
	mi := &file_proto_git_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsResponse) ProtoMessage() {}

func (x *ListCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{13}
}

func (x *ListCommitsResponse) GetCommits() []*CommitInfo {
	if x != nil {
		return x.Commits
	}
	return nil
}

type GetCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Sha           string                 `protobuf:"bytes,3,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitRequest) Reset() {
	*x = GetCommitRequest{}
	mi := &file_proto_git_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitRequest) ProtoMessage() {}

func (x *GetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitRequest.ProtoReflect.Descriptor instead.
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommitRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GetCommitRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetCommitRequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type CommitDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *CommitInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Diff          string                 `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDetail) Reset() {
	*x = CommitDetail{}
	mi := &file_proto_git_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDetail) ProtoMessage() {}

func (x *CommitDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDetail.ProtoReflect.Descriptor instead.
func (*CommitDetail) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{15}
}

func (x *CommitDetail) GetInfo() *CommitInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CommitDetail) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type GetDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Base          string                 `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Head          string                 `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffRequest) Reset() {
	*x = GetDiffRequest{}
	mi := &file_proto_git_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffRequest) ProtoMessage() {}

func (x *GetDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffRequest.ProtoReflect.Descriptor instead.
func (*GetDiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{16}
}

func (x *GetDiffRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GetDiffRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetDiffRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetDiffRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

type GetDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	FilesChanged  int32                  `protobuf:"varint,2,opt,name=files_changed,json=filesChanged,proto3" json:"files_changed,omitempty"`
	Additions     int32                  `protobuf:"varint,3,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int32                  `protobuf:"varint,4,opt,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffResponse) Reset() {
	*x = GetDiffResponse{}
	mi := &file_proto_git_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffResponse) ProtoMessage() {}

func (x *GetDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffResponse.ProtoReflect.Descriptor instead.
func (*GetDiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{17}
}

func (x *GetDiffResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *GetDiffResponse) GetFilesChanged() int32 {
	if x != nil {
		return x.FilesChanged
	}
	return 0
}

func (x *GetDiffResponse) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *GetDiffResponse) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,3,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,4,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	Strategy      string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"` // merge | squash | rebase
	AuthorName    string                 `protobuf:"bytes,6,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail   string                 `protobuf:"bytes,7,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_proto_git_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{18}
}

func (x *MergeRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *MergeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MergeRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *MergeRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *MergeRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *MergeRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *MergeRequest) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

type MergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MergeSha      string                 `protobuf:"bytes,2,opt,name=merge_sha,json=mergeSha,proto3" json:"merge_sha,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Conflicts     []string               `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	mi := &file_proto_git_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{19}
}

func (x *MergeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MergeResponse) GetMergeSha() string {
	if x != nil {
		return x.MergeSha
	}
	return ""
}

func (x *MergeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MergeResponse) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type FileTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTreeRequest) Reset() {
	*x = FileTreeRequest{}
	mi := &file_proto_git_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTreeRequest) ProtoMessage() {}

func (x *FileTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTreeRequest.ProtoReflect.Descriptor instead.
func (*FileTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{20}
}

func (x *FileTreeRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *FileTreeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *FileTreeRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *FileTreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // file | dir
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_git_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{21}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type FileTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTreeResponse) Reset() {
	*x = FileTreeResponse{}
	mi := &file_proto_git_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTreeResponse) ProtoMessage() {}

func (x *FileTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTreeResponse.ProtoReflect.Descriptor instead.
func (*FileTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{22}
}

func (x *FileTreeResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContentRequest) Reset() {
	*x = FileContentRequest{}
	mi := &file_proto_git_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContentRequest) ProtoMessage() {}

func (x *FileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContentRequest.ProtoReflect.Descriptor instead.
func (*FileContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{23}
}

func (x *FileContentRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *FileContentRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *FileContentRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *FileContentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContentResponse) Reset() {
	*x = FileContentResponse{}
	mi := &file_proto_git_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContentResponse) ProtoMessage() {}

func (x *FileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContentResponse.ProtoReflect.Descriptor instead.
func (*FileContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_proto_rawDescGZIP(), []int{24}
}

func (x *FileContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileContentResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileContentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_git_proto protoreflect.FileDescriptor

const file_proto_git_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/git.proto\x12\x13monkeyscloud.git.v1\"E\n" +
	"\x17CreateRepositoryRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"N\n" +
	"\x18CreateRepositoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x17DeleteRepositoryRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"4\n" +
	"\x18DeleteRepositoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x13ListBranchesRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"}\n" +
	"\n" +
	"BranchInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"S\n" +
	"\x14ListBranchesResponse\x12;\n" +
	"\bbranches\x18\x01 \x03(\v2\x1f.monkeyscloud.git.v1.BranchInfoR\bbranches\"p\n" +
	"\x13CreateBranchRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bfrom_ref\x18\x04 \x01(\tR\afromRef\"O\n" +
	"\x14CreateBranchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\"U\n" +
	"\x13DeleteBranchRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"0\n" +
	"\x14DeleteBranchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x86\x01\n" +
	"\x12ListCommitsRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\x80\x02\n" +
	"\n" +
	"CommitInfo\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12!\n" +
	"\fcommitted_at\x18\x05 \x01(\tR\vcommittedAt\x12#\n" +
	"\rfiles_changed\x18\x06 \x01(\x05R\ffilesChanged\x12\x1c\n" +
	"\tadditions\x18\a \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\b \x01(\x05R\tdeletions\"P\n" +
	"\x13ListCommitsResponse\x129\n" +
	"\acommits\x18\x01 \x03(\v2\x1f.monkeyscloud.git.v1.CommitInfoR\acommits\"P\n" +
	"\x10GetCommitRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x10\n" +
	"\x03sha\x18\x03 \x01(\tR\x03sha\"W\n" +
	"\fCommitDetail\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1f.monkeyscloud.git.v1.CommitInfoR\x04info\x12\x12\n" +
	"\x04diff\x18\x02 \x01(\tR\x04diff\"d\n" +
	"\x0eGetDiffRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x12\n" +
	"\x04base\x18\x03 \x01(\tR\x04base\x12\x12\n" +
	"\x04head\x18\x04 \x01(\tR\x04head\"\x86\x01\n" +
	"\x0fGetDiffResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\x12#\n" +
	"\rfiles_changed\x18\x02 \x01(\x05R\ffilesChanged\x12\x1c\n" +
	"\tadditions\x18\x03 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x04 \x01(\x05R\tdeletions\"\xe4\x01\n" +
	"\fMergeRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12#\n" +
	"\rsource_branch\x18\x03 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\x04 \x01(\tR\ftargetBranch\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12\x1f\n" +
	"\vauthor_name\x18\x06 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\a \x01(\tR\vauthorEmail\"~\n" +
	"\rMergeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tmerge_sha\x18\x02 \x01(\tR\bmergeSha\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tconflicts\x18\x04 \x03(\tR\tconflicts\"c\n" +
	"\x0fFileTreeRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"o\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\"L\n" +
	"\x10FileTreeResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.monkeyscloud.git.v1.FileEntryR\aentries\"f\n" +
	"\x12FileContentRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"W\n" +
	"\x13FileContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size2\xc5\b\n" +
	"\n" +
	"GitService\x12o\n" +
	"\x10CreateRepository\x12,.monkeyscloud.git.v1.CreateRepositoryRequest\x1a-.monkeyscloud.git.v1.CreateRepositoryResponse\x12o\n" +
	"\x10DeleteRepository\x12,.monkeyscloud.git.v1.DeleteRepositoryRequest\x1a-.monkeyscloud.git.v1.DeleteRepositoryResponse\x12c\n" +
	"\fListBranches\x12(.monkeyscloud.git.v1.ListBranchesRequest\x1a).monkeyscloud.git.v1.ListBranchesResponse\x12c\n" +
	"\fCreateBranch\x12(.monkeyscloud.git.v1.CreateBranchRequest\x1a).monkeyscloud.git.v1.CreateBranchResponse\x12c\n" +
	"\fDeleteBranch\x12(.monkeyscloud.git.v1.DeleteBranchRequest\x1a).monkeyscloud.git.v1.DeleteBranchResponse\x12`\n" +
	"\vListCommits\x12'.monkeyscloud.git.v1.ListCommitsRequest\x1a(.monkeyscloud.git.v1.ListCommitsResponse\x12U\n" +
	"\tGetCommit\x12%.monkeyscloud.git.v1.GetCommitRequest\x1a!.monkeyscloud.git.v1.CommitDetail\x12T\n" +
	"\aGetDiff\x12#.monkeyscloud.git.v1.GetDiffRequest\x1a$.monkeyscloud.git.v1.GetDiffResponse\x12V\n" +
	"\rMergeBranches\x12!.monkeyscloud.git.v1.MergeRequest\x1a\".monkeyscloud.git.v1.MergeResponse\x12Z\n" +
	"\vGetFileTree\x12$.monkeyscloud.git.v1.FileTreeRequest\x1a%.monkeyscloud.git.v1.FileTreeResponse\x12c\n" +
	"\x0eGetFileContent\x12'.monkeyscloud.git.v1.FileContentRequest\x1a(.monkeyscloud.git.v1.FileContentResponseB*Z(github.com/monkeyscloud/git-server/protob\x06proto3"

var (
	file_proto_git_proto_rawDescOnce sync.Once
	file_proto_git_proto_rawDescData []byte
)

func file_proto_git_proto_rawDescGZIP() []byte {
	file_proto_git_proto_rawDescOnce.Do(func() {
		file_proto_git_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_git_proto_rawDesc), len(file_proto_git_proto_rawDesc)))
	})
	return file_proto_git_proto_rawDescData
}

var file_proto_git_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_git_proto_goTypes = []any{
	(*CreateRepositoryRequest)(nil),  // 0: monkeyscloud.git.v1.CreateRepositoryRequest
	(*CreateRepositoryResponse)(nil), // 1: monkeyscloud.git.v1.CreateRepositoryResponse
	(*DeleteRepositoryRequest)(nil),  // 2: monkeyscloud.git.v1.DeleteRepositoryRequest
	(*DeleteRepositoryResponse)(nil), // 3: monkeyscloud.git.v1.DeleteRepositoryResponse
	(*ListBranchesRequest)(nil),      // 4: monkeyscloud.git.v1.ListBranchesRequest
	(*BranchInfo)(nil),               // 5: monkeyscloud.git.v1.BranchInfo
	(*ListBranchesResponse)(nil),     // 6: monkeyscloud.git.v1.ListBranchesResponse
	(*CreateBranchRequest)(nil),      // 7: monkeyscloud.git.v1.CreateBranchRequest
	(*CreateBranchResponse)(nil),     // 8: monkeyscloud.git.v1.CreateBranchResponse
	(*DeleteBranchRequest)(nil),      // 9: monkeyscloud.git.v1.DeleteBranchRequest
	(*DeleteBranchResponse)(nil),     // 10: monkeyscloud.git.v1.DeleteBranchResponse
	(*ListCommitsRequest)(nil),       // 11: monkeyscloud.git.v1.ListCommitsRequest
	(*CommitInfo)(nil),               // 12: monkeyscloud.git.v1.CommitInfo
	(*ListCommitsResponse)(nil),      // 13: monkeyscloud.git.v1.ListCommitsResponse
	(*GetCommitRequest)(nil),         // 14: monkeyscloud.git.v1.GetCommitRequest
	(*CommitDetail)(nil),             // 15: monkeyscloud.git.v1.CommitDetail
	(*GetDiffRequest)(nil),           // 16: monkeyscloud.git.v1.GetDiffRequest
	(*GetDiffResponse)(nil),          // 17: monkeyscloud.git.v1.GetDiffResponse
	(*MergeRequest)(nil),             // 18: monkeyscloud.git.v1.MergeRequest
	(*MergeResponse)(nil),            // 19: monkeyscloud.git.v1.MergeResponse
	(*FileTreeRequest)(nil),          // 20: monkeyscloud.git.v1.FileTreeRequest
	(*FileEntry)(nil),                // 21: monkeyscloud.git.v1.FileEntry
	(*FileTreeResponse)(nil),         // 22: monkeyscloud.git.v1.FileTreeResponse
	(*FileContentRequest)(nil),       // 23: monkeyscloud.git.v1.FileContentRequest
	(*FileContentResponse)(nil),      // 24: monkeyscloud.git.v1.FileContentResponse
}
var file_proto_git_proto_depIdxs = []int32{
	5,  // 0: monkeyscloud.git.v1.ListBranchesResponse.branches:type_name -> monkeyscloud.git.v1.BranchInfo
	12, // 1: monkeyscloud.git.v1.ListCommitsResponse.commits:type_name -> monkeyscloud.git.v1.CommitInfo
	12, // 2: monkeyscloud.git.v1.CommitDetail.info:type_name -> monkeyscloud.git.v1.CommitInfo
	21, // 3: monkeyscloud.git.v1.FileTreeResponse.entries:type_name -> monkeyscloud.git.v1.FileEntry
	0,  // 4: monkeyscloud.git.v1.GitService.CreateRepository:input_type -> monkeyscloud.git.v1.CreateRepositoryRequest
	2,  // 5: monkeyscloud.git.v1.GitService.DeleteRepository:input_type -> monkeyscloud.git.v1.DeleteRepositoryRequest
	4,  // 6: monkeyscloud.git.v1.GitService.ListBranches:input_type -> monkeyscloud.git.v1.ListBranchesRequest
	7,  // 7: monkeyscloud.git.v1.GitService.CreateBranch:input_type -> monkeyscloud.git.v1.CreateBranchRequest
	9,  // 8: monkeyscloud.git.v1.GitService.DeleteBranch:input_type -> monkeyscloud.git.v1.DeleteBranchRequest
	11, // 9: monkeyscloud.git.v1.GitService.ListCommits:input_type -> monkeyscloud.git.v1.ListCommitsRequest
	14, // 10: monkeyscloud.git.v1.GitService.GetCommit:input_type -> monkeyscloud.git.v1.GetCommitRequest
	16, // 11: monkeyscloud.git.v1.GitService.GetDiff:input_type -> monkeyscloud.git.v1.GetDiffRequest
	18, // 12: monkeyscloud.git.v1.GitService.MergeBranches:input_type -> monkeyscloud.git.v1.MergeRequest
	20, // 13: monkeyscloud.git.v1.GitService.GetFileTree:input_type -> monkeyscloud.git.v1.FileTreeRequest
	23, // 14: monkeyscloud.git.v1.GitService.GetFileContent:input_type -> monkeyscloud.git.v1.FileContentRequest
	1,  // 15: monkeyscloud.git.v1.GitService.CreateRepository:output_type -> monkeyscloud.git.v1.CreateRepositoryResponse
	3,  // 16: monkeyscloud.git.v1.GitService.DeleteRepository:output_type -> monkeyscloud.git.v1.DeleteRepositoryResponse
	6,  // 17: monkeyscloud.git.v1.GitService.ListBranches:output_type -> monkeyscloud.git.v1.ListBranchesResponse
	8,  // 18: monkeyscloud.git.v1.GitService.CreateBranch:output_type -> monkeyscloud.git.v1.CreateBranchResponse
	10, // 19: monkeyscloud.git.v1.GitService.DeleteBranch:output_type -> monkeyscloud.git.v1.DeleteBranchResponse
	13, // 20: monkeyscloud.git.v1.GitService.ListCommits:output_type -> monkeyscloud.git.v1.ListCommitsResponse
	15, // 21: monkeyscloud.git.v1.GitService.GetCommit:output_type -> monkeyscloud.git.v1.CommitDetail
	17, // 22: monkeyscloud.git.v1.GitService.GetDiff:output_type -> monkeyscloud.git.v1.GetDiffResponse
	19, // 23: monkeyscloud.git.v1.GitService.MergeBranches:output_type -> monkeyscloud.git.v1.MergeResponse
	22, // 24: monkeyscloud.git.v1.GitService.GetFileTree:output_type -> monkeyscloud.git.v1.FileTreeResponse
	24, // 25: monkeyscloud.git.v1.GitService.GetFileContent:output_type -> monkeyscloud.git.v1.FileContentResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_git_proto_init() }
func file_proto_git_proto_init() {
	if File_proto_git_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_git_proto_rawDesc), len(file_proto_git_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_git_proto_goTypes,
		DependencyIndexes: file_proto_git_proto_depIdxs,
		MessageInfos:      file_proto_git_proto_msgTypes,
	}.Build()
	File_proto_git_proto = out.File
	file_proto_git_proto_goTypes = nil
	file_proto_git_proto_depIdxs = nil
}
